### ISSUE TITLE
Preciser le contenu des mesures qui sont referencees.

### ISSUE THREAD

**Issue by Edouard-Legoupil** [EnMarche/transformer.en-marche.fr#76]
Par exemple avec des lien sur Legifrance ou Journal Officel, ou des rapports pour avoir les détails de celles-ci... 

Sinon ce site risque de plus apparaître comme un exercice de "communication" que d'information...

**Comment by sp0ker** [comment]
En effet cela serait plus sérieux de pointer vers les articles en questions (ou billets de blog) lorsque cela est "fait".
